FROM php:5.6
MAINTAINER itspoma <itspoma@gmail.com>

# RUN echo "alias ll='ls -la'" >> ~/.bashrc

# RUN curl -sS https://getcomposer.org/installer | php \
#  && mv composer.phar /usr/local/bin/composer

# RUN curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony \
#  && chmod a+x /usr/local/bin/symfony

WORKDIR /app